-- Migration: Add suggested_prompts column to teacher_profiles
-- Stores array of 3 student-facing prompt suggestions
-- Idempotent: safe to re-run

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'teacher_profiles' AND column_name = 'suggested_prompts'
  ) THEN
    ALTER TABLE teacher_profiles ADD COLUMN suggested_prompts JSONB DEFAULT NULL;
  END IF;
END $$;

COMMENT ON COLUMN teacher_profiles.suggested_prompts IS 'Array of 3 student-facing suggestion prompts, generated by AI based on course_info/syllabus';
